name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Use your Docker Hub username as a secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # Use your Docker Hub password or token as a secret

    # Build and Push the Docker image
    - name: Build and Push Docker image
      run: |
        IMAGE_TAG="basanta4043/tag:$(date +%Y%m%d%H%M%S)"
        echo "Building Docker image with tag $IMAGE_TAG"
        docker build . --file Dockerfile --tag $IMAGE_TAG
        docker images  # List images to verify the build
        echo "Pushing image with tag $IMAGE_TAG"
        docker push $IMAGE_TAG
