name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Login to DockerHub or any registry
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Add username as a secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # Add password as a secret

    # Build the Docker image with the desired tag
    - name: Build the Docker image
      run: |
        IMAGE_TAG="basanta4043/tag:$(date +%Y%m%d%H%M%S)"
        docker build . --file Dockerfile --tag $IMAGE_TAG
        echo "Built image with tag $IMAGE_TAG"

    # Push the Docker image to the registry
    - name: Push Docker image
      run: |
        IMAGE_TAG="basanta4043/tag:$(date +%Y%m%d%H%M%S)"
        docker push $IMAGE_TAG
        echo "Pushed image $IMAGE_TAG"
